version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - "sonarQube:sq"
    command: bash -c "curl -fsSL https://get.docker.com | sh && /sbin/tini -- /usr/local/bin/jenkins.sh"
  sonarQube:
    image: sonarqube
    privileged: true
    user: root
    ports:
      - 9000:9000
    container_name: sonarQube
